spring: 
  profiles:
    active:
    - dev
--- 
# 端口号设置
server:
  port: 8001
# mybatis的配置
mybatis:
  # mybatis的配置文件和映射文件
  config-location: classpath:mybatis/mybatis.cfg.xml
  mapper-locations: classpath:mybatis/mapper/**/*.xml
spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      initial-size: 5
      max-total: 5
      min-idle: 5
      max-wait-millis: 200
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true
info:
  app.name: atguigu-microservicecloud-springcloudconfig01
  app.description: 部门服务的提供者动态获取配置文件
  company.name: www.timer.com
  build.groupId: $project.groupId$
  build.artifactId: $project.artifactId$
  build.version: $project.version$
--- 
# 端口号设置
server:
  port: 8001
# mybatis的配置
mybatis:
  # mybatis的配置文件和映射文件
  config-location: classpath:mybatis/mybatis.cfg.xml
  mapper-locations: classpath:mybatis/mapper/**/*.xml
spring:
  profiles: test
  application:
    name: microservicecloud-config-dept-client
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB02
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      initial-size: 5
      max-total: 5
      min-idle: 5
      max-wait-millis: 200
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true
info:
  app.name: atguigu-microservicecloud-springcloudconfig02
  app.description: 部门服务的提供者动态获取配置文件
  company.name: www.timer.com
  build.groupId: $project.groupId$
  build.artifactId: $project.artifactId$
  build.version: $project.version$